### ISSUE TITLE
ValueError in dashboard hook, seen in py2/octo1.4.0

### ISSUE THREAD

**Issue by tedder** [StefanCohen/OctoPrint-Dashboard#147]
Note **I am reporting this based on reviewing a third party's logs**. It may not be reproducible or valid.

Seen in [a random log entry on reddit](https://www.reddit.com/r/octoprint/comments/g9oenz/any_solution_to_stutters_ender_3_with_abl_running), right before a cancellation completes:
```
2020-04-28 21:21:41,361 - octoprint.util.comm - ERROR - Error while processing hook dashboard for phase queued and command G1 X0 Y{machine_depth}:
Traceback (most recent call last):
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint/util/comm.py", line 3332, in _process_command_phase
    hook_results = hook(self, phase, command, command_type, gcode, subcode=subcode, tags=tags)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_dashboard/__init__.py", line 180, in process_gcode
    CmdDict = dict ((x,float(y)) for d,x,y in (re.split('([A-Z])', i) for i in cmd.upper().split()))
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_dashboard/__init__.py", line 180, in <genexpr>
    CmdDict = dict ((x,float(y)) for d,x,y in (re.split('([A-Z])', i) for i in cmd.upper().split()))
ValueError: too many values to unpack
```

Obviously no repro, the {machine_depth} looks suspect to me, but the generator must be getting out of hand for some reason.

**Comment by StefanCohen** [comment]
Thanks fot the feedback. That {machine_depth} string looks suspicious indeed. That's probably supposed to be a Cura macro but it has been unresolved for some reason and passed as a string. I haven't been able to reproduce the error but I guess I could try to add some error handling in the gcode processing preemptively .
